### ISSUE TITLE
get the wrong return values

### ISSUE THREAD

**Issue by TututuXi** [kerner1000/javafx-chart-zooming#3]
```
chart.setOnMouseReleased(new EventHandler<MouseEvent>() {
	@Override
	public void handle(final MouseEvent event) {
	final Bounds bb = chartBackground.sceneToLocal(rect.getBoundsInLocal());
	final double minx = bb.getMinX();
	final double maxx = bb.getMaxX();
	final double miny = bb.getMinY();
	final double maxy = bb.getMaxY();
	doZoom(true, chart.getXAxis().getValueForDisplay(minx), chart.getXAxis().getValueForDisplay(maxx));
	doZoom(false, chart.getYAxis().getValueForDisplay(miny), chart.getYAxis().getValueForDisplay(maxy));
	rect.setWidth(0);
	rect.setHeight(0);
	}
});
```
when I drag and print `miny` and `maxy`, I get negative. Why?

**Comment by kerner1000** [comment]
Because you are selecting an area that (partly) is outside of the axis bounds. That's perfectly normal.

**Comment by TututuXi** [comment]
Hi, 
When I do like that， It disappear
![test](https://user-images.githubusercontent.com/15766876/28853752-58a1441a-7765-11e7-9219-08303ebb2ccc.gif)

I get
```
miny = -326.0
maxy =  -108.0
getValueForDisplay(miny)) = 7.065625
getValueForDisplay(maxy) = 4.6812499999999995
```
However, if I do not put the chart in grid pane, it can work, like that
![test2](https://user-images.githubusercontent.com/15766876/28853936-79ed7336-7766-11e7-8970-d1b08c1945d6.gif)
I get
```
miny = 102.0
maxy = 290.0
getValueForDisplay(miny) = 2.3843749999999995
getValueForDisplay(maxy) = 0.32812499999999994
```

**Comment by kerner1000** [comment]
Hi see you are working on a zoomable MassSpectrum View. What about working on that together? Is the project already on GitHub?

**Comment by lhuangjs** [comment]
I am so sorry. I can' t add you as Collaborators in github because the project is not belong me.

**Comment by TututuXi** [comment]
I am so sorry. I can' t add you as Collaborators in github because the project is not belong me. @kerner1000

**Comment by kerner1000** [comment]
@lhuangjs  OK, but be aware of this project's [license](https://github.com/kerner1000/javafx-chart-zooming/blob/master/LICENSE.txt). If you use this project in a closed source/ commercial project of your own, you need to mention this usage in your own licence statement.

**Comment by TututuXi** [comment]
@kerner1000 ok, I will If I use it.

**Comment by kerner1000** [comment]
Without example code it is hard to tell what is the problem.

**Comment by lhuangjs** [comment]
huangjs2017@gmail.com. It is my email. please sent a email to let me kown your email address and I will seed a example to you. Ok?
