### ISSUE TITLE
Zooming is not working correctly when chart is inside another pane

### ISSUE THREAD

**Issue by kerner1000** [kerner1000/javafx-chart-zooming#4]
Probably the wrong background is used (the root parent instead of the chart parent) to calculate zoom-boundaries.

**Comment by Floxii** [comment]
There is a way to make it work well in this case or not ? Your zoom is so great and I need it in a project, then if there is a solution tell me :)

**Comment by kerner1000** [comment]
Pull requests are welcome! :)

**Comment by dpere326** [comment]
Updating line 313 as shown below worked for me. Thanks!
  final Bounds bb = chartBackground.parentToLocal(rect.getBoundsInParent());

**Comment by govindashrit** [comment]
Thanks, Zoom is perfect !!, Any new version planned with above change. As i have the same issue.
